Switch wsconnector to internal socket client
OpenVoiceOS/ovos-PHAL-plugin-homeassistant pull request #3
Opened 2023-01-12 11:30 UTC by AIIX

- Introduces a custom socket asynchronous HomeAssistantClient that replaces HASS client implementation with minimal changes on connector side
- Fixes all bugs and errors encountered with using the HASS Client

2023-01-14 01:23 UTC, NeonDaniel reviewed
Skimmed changes and the look good, couple bugs from testing (local wss connection):
- After turning off a device on or off in the UI, the new state isn't displayed until I go to a different view and come back (only noticed in grouped view, appeared to work in devices view)

Other less important notes:
- Camera previews work, but playback does not
- When I display grouped, the bottom bar is all `...`, could this be made scrollable?
- All of my rooms have `s` appended (i.e. "Hallways", "Kitchens", "Downstairss"

2023-01-20 06:02 UTC, AIIX commented
This PR additionally now adds support for QR Code based oauth authentication for quicker setups. Additionally bugs mentioned above in the initial review have also now been fixed

2023-01-20 19:20 UTC, NeonDaniel requested changes
I have 19 areas displayed on the home screen, but only 8 are scrollable on the bottom bar before the right scroll arrow becomes grayed out; it stops scrolling after 4 presses if that's relevant

2023-01-24 22:52 UTC, NeonDaniel approved these changes

2023-01-24 22:52 UTC, NeonDaniel commented on requirements.txt
> +ovos-utils>=0.0.27
This could probably be `~=0.0.27` to prevent updating to an incompatible release (i.e. 1.0.0) in the future

2023-01-24 23:11 UTC, merged