Relax ovos-PHAL-plugin-oauth dependency version
OpenVoiceOS/ovos-PHAL-plugin-homeassistant pull request #43
Opened 2023-09-11 18:03 UTC by Ramblurr

2023-09-12 02:37 UTC, mikejgray approved these changes

2023-09-12 03:35 UTC, mikejgray commented
@Ramblurr This looks good to me, but I'd like to make sure all the tests pass. Would you please update `.github/workflows/unit_tests.yml` to the following on your branch?

```yaml
name: Unit Tests
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
    with:
      python_version: "3.8"
```

2023-09-12 07:21 UTC, Ramblurr commented
Done! It needs approval to run: https://github.com/OpenVoiceOS/ovos-PHAL-plugin-homeassistant/actions

2023-09-12 18:05 UTC, NeonDaniel commented
Closes #42

2024-01-03 05:06 UTC, mikejgray commented on requirements.txt
> +ovos-PHAL-plugin-oauth>=0.0.1
@Ramblurr This seems like a good alternative, will that work for your use case?

2024-01-03 21:37 UTC, JarbasAl approved these changes

2024-01-04 05:17 UTC, mikejgray requested changes

2024-01-04 05:17 UTC, mikejgray commented on requirements.txt
> +ovos-PHAL-plugin-oauth>=0.0.1
```suggestion
ovos-PHAL-plugin-oauth~=0.0
```

2024-01-09 02:55 UTC, mikejgray commented
@Ramblurr This change will be applicable when https://github.com/OpenVoiceOS/ovos-PHAL-plugin-homeassistant/pull/48 is merged, which is slated for this week, so I'm going to close this PR in favor of that one. Thank you for calling this out!

2024-01-09 02:55 UTC, closed without merging